name: release-please
on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            -   uses: googleapis/release-please-action@v4
                id: release
            -   uses: actions/checkout@v5
                # these if statements ensure that a publication only occurs when
                # a new release is created:
                if: ${{ steps.release.outputs.release_created }}
            # Build jar
            -   name: Set up JDK 21
                if: ${{ steps.release.outputs.release_created }}
                uses: actions/setup-java@v5
                with:
                    java-version: "21"
                    distribution: "temurin"

            -   name: Setup Gradle
                if: ${{ steps.release.outputs.release_created }}
                uses: gradle/actions/setup-gradle@v4

            -   name: Run chmod to make gradlew executable
                if: ${{ steps.release.outputs.release_created }}
                run: chmod +x ./gradlew

            -   name: Build with Gradle
                if: ${{ steps.release.outputs.release_created }}
                run: ./gradlew build

            -   name: Upload Release Artifact
                if: ${{ steps.release.outputs.release_created }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    gh release upload ${{ steps.release.outputs.tag_name }} build/libs/McDeob-*-all.jar